const sb = window.supabase.createClient(RBC_CONFIG.SUPABASE_URL,RBC_CONFIG.SUPABASE_ANON_KEY);
const esc=s=>{const d=document.createElement('div');d.textContent=s??'';return d.innerHTML};
function card(n){return `<article class="card">${n.image_url?`<img src="${esc(n.image_url)}" alt="">`:''}<span class="muted">${esc(n.category||'Новости')} · ${new Date(n.created_at).toLocaleString('ru-RU')}</span><h3>${esc(n.title)}</h3><p>${esc(n.summary||'')}</p><small>Источник: ${esc(n.source_name||'не указан')}</small></article>`}
async function loadLatest(){const {data}=await sb.from('news').select('*').eq('status','published').order('created_at',{ascending:false}).limit(6);const el=document.querySelector('#latest');if(el)el.innerHTML=(data||[]).map(card).join('')||'<p class="muted">Новостей пока нет.</p>';loadFundraisers('funds')}
async function loadNewsPage(cat=''){let q=sb.from('news').select('*').eq('status','published').order('created_at',{ascending:false}).limit(100);if(cat)q=q.eq('category',cat);const {data}=await q;const el=document.querySelector('#news');if(el)el.innerHTML=(data||[]).map(card).join('')||'<p class="muted">Новостей нет.</p>'}
async function loadFundraisers(target='funds'){const {data}=await sb.from('fundraisers').select('*').eq('status','active').order('created_at',{ascending:false});const el=document.querySelector('#'+target);if(!el)return;el.innerHTML=(data||[]).map(f=>{const p=f.target_amount>0?Math.min(100,(Number(f.current_amount||0)/Number(f.target_amount))*100):0;return `<article class="card">${f.image_url?`<img src="${esc(f.image_url)}" alt="">`:''}<h3>${esc(f.title)}</h3><p>${esc(f.description||'')}</p><b>${Number(f.current_amount||0).toLocaleString('ru-RU')} ${esc(f.currency)} / ${Number(f.target_amount).toLocaleString('ru-RU')} ${esc(f.currency)}</b><div class="progress"><i style="width:${p}%"></i></div><p class="muted">${p.toFixed(0)}%</p><a class="button" href="${esc(f.donation_url)}" target="_blank" rel="noopener">Пожертвовать</a></article>`}).join('')||'<p class="muted">Активных сборов пока нет.</p>'}
async function setupLogin(){document.querySelector('#login').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});msg.textContent=error?error.message:'Готово';if(!error)location.href='index.html'}}
async function setupRegister(){document.querySelector('#register').onsubmit=async e=>{e.preventDefault();const {error}=await sb.auth.signUp({email:email.value,password:password.value,options:{data:{name:name.value}}});msg.textContent=error?error.message:'Проверьте email для подтверждения.'}}
async function loadProfile(){const {data:{user}}=await sb.auth.getUser();const el=document.querySelector('#profile');if(!user){el.innerHTML='<a class="button" href="login.html">Войти</a>';return}const {data:p}=await sb.from('profiles').select('*').eq('id',user.id).single();el.innerHTML=`<div class="panel"><h2>${esc(p?.name||user.email)}</h2><p>${esc(user.email)}</p><p>Роль: <b>${esc(p?.role||'user')}</b></p><button class="button" id="logout">Выйти</button></div>`;logout.onclick=async()=>{await sb.auth.signOut();location.href='index.html'}}
async function setupAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user){location.href='login.html';return}const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).single();if(p?.role!=='admin'){document.body.innerHTML='<main class="container"><h1>403</h1><p>Доступ запрещён.</p></main>';return}loadFundraisers('admin-funds');document.querySelector('#fund-form').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('fundraisers').insert({title:ftitle.value,description:fdesc.value,target_amount:Number(ftarget.value),currency:fcurrency.value.toUpperCase(),image_url:fimage.value||null,donation_url:fdonate.value,end_date:fend.value||null});document.querySelector('#fund-msg').textContent=error?error.message:'Сбор создан';if(!error){e.target.reset();loadFundraisers('admin-funds')}}}
if(location.pathname.endsWith('index.html')||location.pathname==='/'){loadLatest()}